version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-ideatech
    ports:
      - "3000:3000"
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
